// Copyright 2025-2026 Excited Waves. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

#if ENGINE_MAJOR_VERSION >= 5
#define EWACOUSTICS_UE5_OR_LATER 1
#else
#define EWACOUSTICS_UE5_OR_LATER 0
#endif

#if ENGINE_MAJOR_VERSION == 4 && ENGINE_MINOR_VERSION >= 27
#define EWACOUSTICS_UE427_OR_LATER 1
#else
#define EWACOUSTICS_UE427_OR_LATER 0
#endif

#if ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 1)
#define EWACOUSTICS_UE51_OR_LATER 1
#else
#define EWACOUSTICS_UE51_OR_LATER 0
#endif

#ifndef EWACOUSTICS_WITH_CHAOS
#define EWACOUSTICS_WITH_CHAOS 0
#endif
